### ISSUE TITLE
感觉构造函数判断 key 和 iv 为空字符串比较清真

### ISSUE THREAD

**Issue by lindexi** [EdiWang/DotNet-Samples#1]
https://github.com/EdiWang/DotNet-Samples/blob/c54d49b3fcc80409c7bb73ba994522dc985a0e50/AspNet-AES-Non-DPAPI/AspNetAESNonDp/Core/EncryptionService.cs#L21

这里只是判断两个都为空的情况，还有一个为空的情况，和虽然存在值但是空字符串的情况

**Comment by lindexi** [comment]
刚好今天在找 dotnet core的加密算法就看到了你的仓库，多谢大佬

**Comment by EdiWang** [comment]
我的想法是只允许这两个参数同时有值，或者同时为空。可以重构一下，抽一个类出来包装这两个参数。
